# Florent Kirchner			-- LogiCal
# Makefile


# Variable definition

RESULT=fsp
SOURCES=core.ml commands.ml print.ml interpreter.ml parser.mly lexer.mll main.ml
TRASH=parser.output

-include OCamlMakefile
