environ

begin

consider A1,A2 being set;
defpred A[] means A1 = A2;

consider B1,B2 being set;
defpred B[] means B1 = B2;

consider C1,C2 being set;
defpred C[] means C1 = C2;

consider D1,D2 being set;
defpred D[] means D1 = D2;

theorem t1:
 A[] implies
  ((A[] implies B[]) implies
  ((A[] implies C[]) implies
  ((B[] implies (C[] implies D[])) implies
  D[])))
proof
 assume a: A[];
 assume ab: (A[] implies B[]);
 assume ac: (A[] implies C[]);
 assume bcd: B[] implies (C[] implies D[]);
 B[] proof
  thus thesis by ab,a;
 end;
 thus thesis by bcd;
::>           *4,4
end;

theorem t2:
 A[] implies
  ((A[] implies B[]) implies
  ((A[] implies C[]) implies
  ((B[] implies (C[] implies D[])) implies
  D[])))
proof
 assume a: A[];
 assume ab: (A[] implies B[]);
 assume ac: (A[] implies C[]);
 assume bcd: B[] implies (C[] implies D[]);
a2: A[] by a;
b:  B[] by ab,a2;
c:  C[] by ac,a2;
 thus thesis by bcd,b,c;
end;
::>
::> 4: This inference is not accepted
